import type Phaser from "phaser";
import type { ItemId } from "../sim/types";

const baseUrl = import.meta.env.BASE_URL.endsWith("/") ? import.meta.env.BASE_URL : `${import.meta.env.BASE_URL}/`;
export const GRID_DUNGEON_ASSET_BASE = `${baseUrl}assets/grid-dungeon`;
export const GRID_DUNGEON_ASSET_KEY_PREFIX = "grid-dungeon:";

export const GRID_DUNGEON_ASSETS = [
  { id: "floor-normal", file: "tiles/floor-normal.png" },
  { id: "floor-lit", file: "tiles/floor-lit.png" },
  { id: "floor-memory", file: "tiles/floor-memory.png" },
  { id: "floor-fog", file: "tiles/floor-fog.png" },
  { id: "floor-exit", file: "tiles/floor-exit.png" },
  { id: "wall-horizontal", file: "walls/wall-horizontal.png" },
  { id: "wall-vertical", file: "walls/wall-vertical.png" },
  { id: "wall-door-blocked", file: "walls/wall-door-blocked.png" },
  { id: "prop-wall-lamp", file: "props/prop-wall-lamp.png" },
  { id: "prop-cache-box", file: "props/prop-cache-box.png" },
  { id: "prop-debris", file: "props/prop-debris.png" },
  { id: "prop-red-leak", file: "props/prop-red-leak.png" },
  { id: "actor-player", file: "actors/actor-player.png" },
  { id: "actor-enemy", file: "actors/actor-enemy.png" },
  { id: "actor-enemy-hint", file: "actors/actor-enemy-hint.png" },
  { id: "item-pistol", file: "items/item-pistol.png" },
  { id: "item-bandage", file: "items/item-bandage.png" },
  { id: "item-long-knife", file: "items/item-long-knife.png" },
  { id: "item-trap", file: "items/item-trap.png" },
  { id: "item-glasses", file: "items/item-glasses.png" },
  { id: "item-glow-stick", file: "items/item-glow-stick.png" },
  { id: "item-echo-needle", file: "items/item-echo-needle.png" },
  { id: "item-weighted-grip", file: "items/item-weighted-grip.png" },
  { id: "item-blade-oil", file: "items/item-blade-oil.png" },
  { id: "item-lime-powder", file: "items/item-lime-powder.png" },
  { id: "item-throwing-knife", file: "items/item-throwing-knife.png" },
  { id: "item-sleeve-stone", file: "items/item-sleeve-stone.png" },
  { id: "item-ice-awl", file: "items/item-ice-awl.png" },
  { id: "item-caltrops", file: "items/item-caltrops.png" },
  { id: "item-hook-rope", file: "items/item-hook-rope.png" },
  { id: "item-acid-vial", file: "items/item-acid-vial.png" },
  { id: "item-old-magazine", file: "items/item-old-magazine.png" },
  { id: "item-thick-cloth", file: "items/item-thick-cloth.png" },
  { id: "item-bracer", file: "items/item-bracer.png" },
  { id: "item-smoke-ball", file: "items/item-smoke-ball.png" },
  { id: "item-painkiller", file: "items/item-painkiller.png" },
  { id: "item-coagulation-powder", file: "items/item-coagulation-powder.png" },
  { id: "item-wood-shield", file: "items/item-wood-shield.png" },
  { id: "item-soft-shoes", file: "items/item-soft-shoes.png" },
  { id: "item-steady-charm", file: "items/item-steady-charm.png" },
  { id: "item-adrenaline-shot", file: "items/item-adrenaline-shot.png" },
  { id: "item-splint", file: "items/item-splint.png" },
  { id: "item-lens", file: "items/item-lens.png" },
  { id: "item-counting-beads", file: "items/item-counting-beads.png" },
  { id: "item-notebook", file: "items/item-notebook.png" },
  { id: "item-scent-powder", file: "items/item-scent-powder.png" },
  { id: "item-black-cloth", file: "items/item-black-cloth.png" },
  { id: "item-bell-wire", file: "items/item-bell-wire.png" },
  { id: "item-polarized-lens", file: "items/item-polarized-lens.png" },
  { id: "item-marked-coin", file: "items/item-marked-coin.png" },
  { id: "item-voice-whistle", file: "items/item-voice-whistle.png" },
  { id: "item-breath-cord", file: "items/item-breath-cord.png" },
  { id: "item-rib-hook", file: "items/item-rib-hook.png" },
  { id: "item-ankle-line", file: "items/item-ankle-line.png" },
  { id: "item-chase-spur", file: "items/item-chase-spur.png" },
  { id: "item-counter-plate", file: "items/item-counter-plate.png" },
  { id: "item-panic-nail", file: "items/item-panic-nail.png" },
  { id: "item-focus-thread", file: "items/item-focus-thread.png" },
  { id: "item-soot-hook", file: "items/item-soot-hook.png" },
  { id: "item-venom-saw", file: "items/item-venom-saw.png" },
  { id: "item-blood-knot", file: "items/item-blood-knot.png" },
  { id: "item-frost-latch", file: "items/item-frost-latch.png" },
  { id: "item-lens-thread", file: "items/item-lens-thread.png" },
  { id: "item-stitch-kit", file: "items/item-stitch-kit.png" },
  { id: "item-tripwire-spool", file: "items/item-tripwire-spool.png" },
  { id: "item-red-compass", file: "items/item-red-compass.png" },
  { id: "item-smoke-needle", file: "items/item-smoke-needle.png" },
  { id: "item-thorn-plate", file: "items/item-thorn-plate.png" },
  { id: "item-salve-tin", file: "items/item-salve-tin.png" },
  { id: "item-field-ration", file: "items/item-field-ration.png" },
  { id: "item-charcoal-tablet", file: "items/item-charcoal-tablet.png" },
  { id: "item-pressure-bandage", file: "items/item-pressure-bandage.png" },
  { id: "item-heat-pad", file: "items/item-heat-pad.png" },
  { id: "item-blood-sponge", file: "items/item-blood-sponge.png" },
  { id: "item-mercy-thread", file: "items/item-mercy-thread.png" },
  { id: "item-emergency-syringe", file: "items/item-emergency-syringe.png" },
  { id: "item-sharpening-stone", file: "items/item-sharpening-stone.png" },
  { id: "item-glass-spike", file: "items/item-glass-spike.png" },
  { id: "item-tinder-vial", file: "items/item-tinder-vial.png" },
  { id: "item-poison-needle", file: "items/item-poison-needle.png" },
  { id: "item-barbed-line", file: "items/item-barbed-line.png" },
  { id: "item-frost-nail", file: "items/item-frost-nail.png" },
  { id: "item-antidote-tablet", file: "items/item-antidote-tablet.png" },
  { id: "item-insulation-cloth", file: "items/item-insulation-cloth.png" },
  { id: "item-signal-mirror", file: "items/item-signal-mirror.png" },
  { id: "item-folded-map", file: "items/item-folded-map.png" },
  { id: "item-runner-knot", file: "items/item-runner-knot.png" },
  { id: "item-signal-flare", file: "items/item-signal-flare.png" },
  { id: "item-lead-wrap", file: "items/item-lead-wrap.png" },
  { id: "item-ankle-spring", file: "items/item-ankle-spring.png" },
  { id: "item-cracked-scope", file: "items/item-cracked-scope.png" },
  { id: "item-spark-fuse", file: "items/item-spark-fuse.png" },
  { id: "item-second-breath", file: "items/item-second-breath.png" },
  { id: "item-rust-cloud", file: "items/item-rust-cloud.png" },
  { id: "item-coal-beads", file: "items/item-coal-beads.png" },
  { id: "item-toxin-skein", file: "items/item-toxin-skein.png" },
  { id: "item-cold-rivet", file: "items/item-cold-rivet.png" },
  { id: "item-crit-hook", file: "items/item-crit-hook.png" },
  { id: "item-guard-breaker", file: "items/item-guard-breaker.png" },
  { id: "item-servo-heel", file: "items/item-servo-heel.png" },
  { id: "item-mnemonic-plate", file: "items/item-mnemonic-plate.png" },
  { id: "item-knuckle-core", file: "items/item-knuckle-core.png" },
  { id: "item-exit-charm", file: "items/item-exit-charm.png" },
  { id: "item-opener-gear", file: "items/item-opener-gear.png" },
  { id: "item-first-glint", file: "items/item-first-glint.png" },
  { id: "item-pilot-flame", file: "items/item-pilot-flame.png" },
  { id: "item-rawhide-guard", file: "items/item-rawhide-guard.png" },
  { id: "item-second-gear", file: "items/item-second-gear.png" },
  { id: "item-coolant-breath", file: "items/item-coolant-breath.png" },
  { id: "item-second-sight", file: "items/item-second-sight.png" },
  { id: "item-venom-timer", file: "items/item-venom-timer.png" },
  { id: "item-long-fuse", file: "items/item-long-fuse.png" },
  { id: "item-fatigue-tax", file: "items/item-fatigue-tax.png" },
  { id: "item-bunker-prayer", file: "items/item-bunker-prayer.png" },
  { id: "item-escape-count", file: "items/item-escape-count.png" },
  { id: "item-spring-step", file: "items/item-spring-step.png" },
  { id: "item-dust-kicker", file: "items/item-dust-kicker.png" },
  { id: "item-slip-venom", file: "items/item-slip-venom.png" },
  { id: "item-dodge-reader", file: "items/item-dodge-reader.png" },
  { id: "item-guard-lens", file: "items/item-guard-lens.png" },
  { id: "item-brace-piston", file: "items/item-brace-piston.png" },
  { id: "item-shield-spark", file: "items/item-shield-spark.png" },
  { id: "item-calm-mouthpiece", file: "items/item-calm-mouthpiece.png" },
  { id: "item-wound-motor", file: "items/item-wound-motor.png" },
  { id: "item-crack-reader", file: "items/item-crack-reader.png" },
  { id: "item-crush-salt", file: "items/item-crush-salt.png" },
  { id: "item-ember-step", file: "items/item-ember-step.png" },
  { id: "item-heat-read", file: "items/item-heat-read.png" },
  { id: "item-ash-threshold", file: "items/item-ash-threshold.png" },
  { id: "item-toxic-focus", file: "items/item-toxic-focus.png" },
  { id: "item-bitter-mouth", file: "items/item-bitter-mouth.png" },
  { id: "item-green-pulse", file: "items/item-green-pulse.png" },
  { id: "item-ice-step", file: "items/item-ice-step.png" },
  { id: "item-cold-reader", file: "items/item-cold-reader.png" },
  { id: "item-shatter-pin", file: "items/item-shatter-pin.png" },
  { id: "item-crit-lens", file: "items/item-crit-lens.png" },
  { id: "item-white-spark", file: "items/item-white-spark.png" },
  { id: "item-snap-sinew", file: "items/item-snap-sinew.png" },
  { id: "item-pain-wheel", file: "items/item-pain-wheel.png" },
  { id: "item-blood-map", file: "items/item-blood-map.png" },
  { id: "item-recoil-plate", file: "items/item-recoil-plate.png" },
  { id: "item-overrun-chain", file: "items/item-overrun-chain.png" },
  { id: "item-hard-receipt", file: "items/item-hard-receipt.png" },
  { id: "item-marrow-coin", file: "items/item-marrow-coin.png" },
  { id: "item-breakwater-splint", file: "items/item-breakwater-splint.png" },
  { id: "item-trauma-scan", file: "items/item-trauma-scan.png" },
  { id: "item-last-ice", file: "items/item-last-ice.png" },
  { id: "item-last-match", file: "items/item-last-match.png" },
  { id: "item-data-spur", file: "items/item-data-spur.png" }
] as const;

export type GridDungeonAssetId = (typeof GRID_DUNGEON_ASSETS)[number]["id"];

const ITEM_ICON_ASSETS: Partial<Record<ItemId, GridDungeonAssetId>> = {
  pistol: "item-pistol",
  bandage: "item-bandage",
  "long-knife": "item-long-knife",
  trap: "item-trap",
  glasses: "item-glasses",
  glow: "item-glow-stick",
  echo: "item-echo-needle",
  "weighted-grip": "item-weighted-grip",
  "blade-oil": "item-blade-oil",
  "lime-powder": "item-lime-powder",
  "throwing-knife": "item-throwing-knife",
  "sleeve-stone": "item-sleeve-stone",
  "ice-awl": "item-ice-awl",
  caltrops: "item-caltrops",
  "hook-rope": "item-hook-rope",
  "acid-vial": "item-acid-vial",
  "old-magazine": "item-old-magazine",
  "thick-cloth": "item-thick-cloth",
  bracer: "item-bracer",
  "smoke-ball": "item-smoke-ball",
  painkiller: "item-painkiller",
  "coagulation-powder": "item-coagulation-powder",
  "wood-shield": "item-wood-shield",
  "soft-shoes": "item-soft-shoes",
  "steady-charm": "item-steady-charm",
  "adrenaline-shot": "item-adrenaline-shot",
  splint: "item-splint",
  lens: "item-lens",
  "counting-beads": "item-counting-beads",
  notebook: "item-notebook",
  "scent-powder": "item-scent-powder",
  "black-cloth": "item-black-cloth",
  "bell-wire": "item-bell-wire",
  "polarized-lens": "item-polarized-lens",
  "marked-coin": "item-marked-coin",
  "voice-whistle": "item-voice-whistle",
  "rib-hook": "item-rib-hook",
  "ankle-line": "item-ankle-line",
  "chase-spur": "item-chase-spur",
  "counter-plate": "item-counter-plate",
  "panic-nail": "item-panic-nail",
  "focus-thread": "item-focus-thread",
  "breath-cord": "item-breath-cord",
  "sharpening-stone": "item-sharpening-stone",
  "glass-spike": "item-glass-spike",
  "tinder-vial": "item-tinder-vial",
  "poison-needle": "item-poison-needle",
  "barbed-line": "item-barbed-line",
  "frost-nail": "item-frost-nail",
  "antidote-tablet": "item-antidote-tablet",
  "insulation-cloth": "item-insulation-cloth",
  "signal-mirror": "item-signal-mirror",
  "folded-map": "item-folded-map",
  "runner-knot": "item-runner-knot",
  "signal-flare": "item-signal-flare",
  "soot-hook": "item-soot-hook",
  "venom-saw": "item-venom-saw",
  "blood-knot": "item-blood-knot",
  "frost-latch": "item-frost-latch",
  "lens-thread": "item-lens-thread",
  "stitch-kit": "item-stitch-kit",
  "tripwire-spool": "item-tripwire-spool",
  "red-compass": "item-red-compass",
  "smoke-needle": "item-smoke-needle",
  "thorn-plate": "item-thorn-plate",
  "salve-tin": "item-salve-tin",
  "field-ration": "item-field-ration",
  "charcoal-tablet": "item-charcoal-tablet",
  "pressure-bandage": "item-pressure-bandage",
  "heat-pad": "item-heat-pad",
  "blood-sponge": "item-blood-sponge",
  "mercy-thread": "item-mercy-thread",
  "emergency-syringe": "item-emergency-syringe",
  "lead-wrap": "item-lead-wrap",
  "ankle-spring": "item-ankle-spring",
  "cracked-scope": "item-cracked-scope",
  "spark-fuse": "item-spark-fuse",
  "second-breath": "item-second-breath",
  "rust-cloud": "item-rust-cloud",
  "coal-beads": "item-coal-beads",
  "toxin-skein": "item-toxin-skein",
  "cold-rivet": "item-cold-rivet",
  "crit-hook": "item-crit-hook",
  "guard-breaker": "item-guard-breaker",
  "servo-heel": "item-servo-heel",
  "mnemonic-plate": "item-mnemonic-plate",
  "knuckle-core": "item-knuckle-core",
  "exit-charm": "item-exit-charm",
  "opener-gear": "item-opener-gear",
  "first-glint": "item-first-glint",
  "pilot-flame": "item-pilot-flame",
  "rawhide-guard": "item-rawhide-guard",
  "second-gear": "item-second-gear",
  "coolant-breath": "item-coolant-breath",
  "second-sight": "item-second-sight",
  "venom-timer": "item-venom-timer",
  "long-fuse": "item-long-fuse",
  "fatigue-tax": "item-fatigue-tax",
  "bunker-prayer": "item-bunker-prayer",
  "escape-count": "item-escape-count",
  "spring-step": "item-spring-step",
  "dust-kicker": "item-dust-kicker",
  "slip-venom": "item-slip-venom",
  "dodge-reader": "item-dodge-reader",
  "guard-lens": "item-guard-lens",
  "brace-piston": "item-brace-piston",
  "shield-spark": "item-shield-spark",
  "calm-mouthpiece": "item-calm-mouthpiece",
  "wound-motor": "item-wound-motor",
  "crack-reader": "item-crack-reader",
  "crush-salt": "item-crush-salt",
  "ember-step": "item-ember-step",
  "heat-read": "item-heat-read",
  "ash-threshold": "item-ash-threshold",
  "toxic-focus": "item-toxic-focus",
  "bitter-mouth": "item-bitter-mouth",
  "green-pulse": "item-green-pulse",
  "ice-step": "item-ice-step",
  "cold-reader": "item-cold-reader",
  "shatter-pin": "item-shatter-pin",
  "crit-lens": "item-crit-lens",
  "white-spark": "item-white-spark",
  "snap-sinew": "item-snap-sinew",
  "pain-wheel": "item-pain-wheel",
  "blood-map": "item-blood-map",
  "recoil-plate": "item-recoil-plate",
  "overrun-chain": "item-overrun-chain",
  "hard-receipt": "item-hard-receipt",
  "marrow-coin": "item-marrow-coin",
  "breakwater-splint": "item-breakwater-splint",
  "trauma-scan": "item-trauma-scan",
  "last-ice": "item-last-ice",
  "last-match": "item-last-match",
  "data-spur": "item-data-spur",
  "burning-enchant-gem": "item-tinder-vial",
  "venomous-enchant-gem": "item-poison-needle",
  "frost-enchant-gem": "item-frost-nail",
  "blood-enchant-gem": "item-blood-knot",
  "deadly-enchant-gem": "item-crit-hook",
  "radiant-enchant-gem": "item-white-spark"
};

/** Returns the stable Phaser texture key for a grid-dungeon asset id. */
export function gridDungeonAssetKey(id: GridDungeonAssetId): string {
  return `${GRID_DUNGEON_ASSET_KEY_PREFIX}${id}`;
}

/** Returns the public URL for a grid-dungeon asset id. */
export function gridDungeonAssetUrl(id: GridDungeonAssetId): string {
  const asset = GRID_DUNGEON_ASSETS.find((entry) => entry.id === id);
  if (!asset) throw new Error(`Unknown grid dungeon asset: ${id}`);
  return `${GRID_DUNGEON_ASSET_BASE}/${asset.file}`;
}

/** Preloads the render-layer assets used by the Phaser grid scene. */
export function preloadGridDungeonAssets(scene: Phaser.Scene): void {
  for (const asset of GRID_DUNGEON_ASSETS) {
    const key = gridDungeonAssetKey(asset.id);
    if (!scene.textures.exists(key)) {
      scene.load.image(key, `${GRID_DUNGEON_ASSET_BASE}/${asset.file}`);
    }
  }
}

/** Returns a DOM-usable item icon URL when a produced icon exists. */
export function itemIconUrl(itemId: ItemId): string | undefined {
  const iconAsset = ITEM_ICON_ASSETS[itemId];
  return iconAsset ? gridDungeonAssetUrl(iconAsset) : undefined;
}
